shanpinApi:
  base_url: 'http://shanpinapi.51job.com'
  account:
    huahua_account: &mobile_huahua '18275691113'
    jing_account: &mobile_jing '18275691111'
  base_params:
    version: '100'
    productname: "51mdd_agent_pc"
    brokerid: ${brokerid}
    key: ${key}
    timestamp: ${timestamp}
    source: "pc"
    sign: ${sign}

  agent_login:
    login_method: 'post'
    login_url: '/user/login.php'
    params:
      version: '100'
      productname: "51mdd_agent_pc"
      brokerid: ''
      key: ''
      timestamp: ${timestamp}
      source: "pc"
      sign: ${sign}
    data:
      mobile: *mobile_jing
      phonecode: ${verifycode}
      source: "pc"

  agent_sms_code:
    sms_method: 'post'
    sms_url: '/user/send_phone_code.php'
    data:
      mobile: *mobile_jing

  sql:
    sqlserver:
      host: '10.100.2.142'
      user: 'sa'
      pwd: 'abc123!'
      db: 'sms'

    mysqlserver:
      host: '10.100.3.241'
      user: 'root'
      pwd: 'S7h26k*4&ds*'
      db: '51mdd'

    redisserver:
      host: '10.100.3.225'
      port: '6380'
      db: '0'
      password: '3ebc6626'

